# Generated by Django 4.0 on 2021-12-14 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_test0_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateField(verbose_name='date published')),
                ('text_data', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PostToTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=10)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.posts')),
            ],
        ),
        migrations.DeleteModel(
            name='test0',
        ),
    ]
